// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/piotr-rusin/playing-with-golang/internal/app/mga/todo/todoadapter/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
